"""Shared enum-like constant dictionaries for DRS/BMG/FXB formats."""
from __future__ import annotations

MagicValues = {
    "CDspJointMap": -1340635850,
    "CGeoMesh": 100449016,
    "CGeoOBBTree": -933519637,
    "CSkSkinInfo": -761174227,
    "CDspMeshFile": -1900395636,
    "DrwResourceMeta": -183033339,
    "collisionShape": 268607026,
    "CGeoPrimitiveContainer": 1396683476,
    "CSkSkeleton": -2110567991,
    "CDrwLocatorList": 735146985,
    "AnimationSet": -475734043,
    "AnimationTimings": -1403092629,
    "EffectSet": 688490554,
}

AnimationType = {
    "CastResolve": 0,
    "Spawn": 1,
    "Melee": 2,
    "Channel": 3,
    "ModeSwitch": 4,
    "WormMovement": 5,
}

LocatorClass = {
    0: "HealthBar",
    1: "DestructiblePart",
    2: "Construction",
    3: "Turret",
    4: "FxbIdle",
    5: "Wheel",
    6: "StaticPerm",
    7: "Unknown7",
    8: "DynamicPerm",
    9: "DamageFlameSmall",
    10: "DamageFlameSmallSmoke",
    11: "DamageFlameLarge",
    12: "DamageSmokeOnly",
    13: "DamageFlameHuge",
    14: "SpellCast",
    15: "SpellHitAll",
    16: "Hit",
    29: "Projectile_Spawn",
}

SoundType = {
    "Impact": 0,
    "Step": 1,
    "Spawn": 3,
    "Cheer": 5,
    "Fight": 8,
}

TrackType = {
    "Unknown": -1,
    "Translate": 0,
    "Rotate": 1,
    "Scale": 2,
    "Anim": 3,
    "Color": 4,
    "Alpha": 5,
    "Size": 6,
    "Time": 7,
    "BlendMode": 8,
    "Light_Range": 9,
    "Start_Color": 10,
    "End_Color": 11,
    "Start_Alpha": 12,
    "End_Alpha": 13,
    "Start_Radiance": 14,
    "End_Radiance": 15,
    "Start_Size": 16,
    "End_Size": 17,
    "StartEnd_Weight": 18,
    "Random_Color": 19,
    "Random_Luminance": 20,
    "Random_Size": 21,
    "Particle_BlendMode": 22,
    "Use_Lighting": 23,
    "Shape": 24,
    "Force": 25,
    "Force_Direction": 26,
    "Force_Variance": 27,
    "Force_Gravity": 28,
    "Phase_Variance": 29,
    "Phase_Start": 30,
    "Rotation_Speed": 31,
    "Emitter_Geometry": 32,
    "Speed_Factor": 33,
    "Playback_Mode": 34,
    "Random_Force_Factor": 35,
    "Particles": 36,
    "Trail_Length": 37,
    "Use_Radiance": 38,
    "Rotation_Offset": 39,
    "Radiance": 40,
    "Shape2": 41,
    "Shape3": 42,
    "AlphaTest": 43,
    "Synchrony": 44,
    "Radius": 45,
    "Radius_Weight": 46,
    "Phase": 47,
    "Frequency": 48,
    "Height_Influence": 49,
    "Sine_Size": 50,
    "Particle_Texture_Division": 51,
    "Texture_Division_U": 52,
    "Texture_Division_V": 53,
    "Texture_Display": 54,
    "Optical_Density": 55,
    "Start_Emissive_Color": 56,
    "End_Emissive_Color": 57,
    "HDR_Exponent": 58,
    "Glow_Alpha": 59,
    "Time_Address": 60,
    "Shadow_Mode": 61,
    "Hardness_Modifier": 62,
    "Particle_Mode": 63,
    "Distortion_FallOff": 64,
    "Offset_Towards_Camera": 65,
    "Alignment_Axis": 66,
    "Pivot_Point": 67,
    "Twosided": 68,
    "BillBoard_Mode": 69,
    "Distortion_FallOff_Dup_1": 70,
    "Hardness_Modifier_Dup_1": 71,
    "Force_Dup_1": 72,
    "Range": 73,
    "Power": 74,
    "Ground_Level": 75,
    "Mass": 76,
    "Volume": 77,
    "Min_Falloff": 78,
    "Max_Falloff": 79,
    "Pitch_Min": 80,
    "Amplitude_Translate": 81,
    "Frequency_Translate": 82,
    "Amplitude_Rotate": 83,
    "Frequency_Rotate": 84,
    "Min_Falloff_Dup_1": 85,
    "Max_Falloff_Dup_1": 86,
    "Add_Translate": 87,
    "Add_Rotate": 88,
    "Size_SfpEmitter_Area": 89,
    "Alpha_Scale": 90,
    "Alpha_Offset": 91,
    "Alpha_Test": 92,
    "Lighting": 93,
    "Fade_Source": 94,
    "Fade_Target": 95,
    "Depth_Sort": 96,
    "Gravity": 97,
    "Dampening": 98,
    "Scale_Dup_1": 99,
    "Opening_Angle_H": 100,
    "Opening_Angle_V": 101,
    "Velocity": 102,
    "Velocity_Variation": 103,
    "Lifetime": 104,
    "Lifetime_Variation": 105,
    "Rate": 106,
    "Rate_Variation": 107,
    "Mass_Dup_1": 108,
    "Mass_Variation": 109,
    "Strength": 110,
    "Size_SfpEmitter_Particle": 111,
    "Size_Variation": 112,
    "RampFloat_1_Input": 113,
    "RampFloat_2_Input": 114,
    "RampVector3_1_Input": 115,
    "RampVector3_2_Input": 116,
    "RampFloat_1_Output": 117,
    "RampFloat_2_Output": 118,
    "RampVector3_1_Output": 119,
    "RampVector3_2_Output": 120,
    "Audio": 121,
    "Distort": 122,
    "Distort_Amp": 123,
    "Texture_BlendMode": 124,
    "MeshType": 125,
    "InheritForce": 126,
    "Distort_Offset": 127,
    "Distort_Speed": 128,
    "FixEmitter": 129,
    "FixAxis": 130,
    "Noise_Scale": 131,
    "Texture_Index": 132,
    "Distort_Twist": 133,
    "Scale_Space": 134,
    "Rotation_Space": 135,
    "Mesh_Center": 136,
    "Disable_By_Depth": 137,
    "Normal_Towards_Target": 138,
    "Target": 139,
    "Distort_Scale": 140,
    "Weight": 141,
    "Animation_Pass": 142,
    "Subdivision": 143,
    "Animation_Start_Time": 144,
    "Emitter_Shape": 145,
    "Shape_Thickness": 146,
    "Shape_Angle_H": 147,
    "Shape_Angle_V": 148,
    "Pt1_Orientation": 149,
    "Distort_Max_Speed": 150,
    "Distort_Length": 151,
    "Pitch_Max": 152,
    "Kill_Radius": 153,
    "Particle_Distort_Vec": 154,
    "Uniform_Force": 155,
    "Rotation_Speed_Dup_1": 156,
    "Rotation_Min_Falloff": 157,
    "Rotation_Max_Falloff": 158,
    "Rotation_Tube_Height": 159,
    "Shadow_Pass": 160,
    "Emitter_Emitter_Quota": 161,
    "Emitter_Emitter_Index": 162,
    "Type": 163,
    "Effect_Alpha": 164,
    "Inherit_Alpha": 165,
    "LOD_Bias": 166,
    "Group_Collision": 167,
    "Offset_Mode": 168,
    "Trail_Alignment": 169,
    "Start_Width": 170,
    "End_Width": 171,
    "Start_Fadeout": 172,
    "Lifetime_Dup_1": 173,
    "Min_Segment_Length": 174,
    "Trail_Interpolation": 175,
    "RampFloat_1_Input_Dup_1": 176,
    "RampFloat_2_Input_Dup_1": 177,
    "RampVector3_1_Input_Dup_1": 178,
    "RampVector3_2_Input_Dup_1": 179,
    "RampFloat_1_Output_Dup_1": 180,
    "RampFloat_2_Output_Dup_1": 181,
    "RampVector3_1_Output_Dup_1": 182,
    "RampVector3_2_Output_Dup_1": 183,
    "Distort_Variation": 184,
    "Texture_Offset": 185,
    "Texture_Zoom": 186,
    "InheritVelocity": 187,
    "DepthWriteThreshold": 188,
    "Torque": 189,
}

TrackDim = {
    "TimeElapsed": 0,
    "TimeScaled": 1,
    "TimeRemaining": 2,
    "TimeAbsolute": 3,
    "Size": 4,
    "Power": 5,
    "Random": 6,
}

TrackMode = {
    "Loop": 0,
    "Bounce": 1,
    "Clamp": 2,
}

TrackInterpolation = {
    "Linear": 0,
    "Bezier": 1,
}

TrackEvaluation = {
    "Track": 0,
    "Ramp": 1,
}

InformationIndices = {
    "AnimatedUnit": {  # AnimatedInteractableObjectNoCollisionWithEffects
        "CGeoMesh": 1,
        "CGeoOBBTree": 8,
        "CDspJointMap": 7,
        "CSkSkinInfo": 9,
        "CSkSkeleton": 4,
        "CDspMeshFile": 5,
        "CDrwLocatorList": 3,
        "DrwResourceMeta": 11,
        "AnimationSet": 10,
        "AnimationTimings": 6,
        "EffectSet": 2,
    },
    "StaticObjectCollision": {
        "CGeoMesh": 1,
        "CGeoOBBTree": 5,
        "CDspJointMap": 4,
        "CDspMeshFile": 3,
        "DrwResourceMeta": 6,
        "CGeoPrimitiveContainer": 2,
        "collisionShape": 7,
    },
    "StaticObjectNoCollision": {
        "CGeoMesh": 1,
        "CGeoOBBTree": 4,
        "CDspJointMap": 3,
        "CDspMeshFile": 2,
        "DrwResourceMeta": 5,
    },
    "AnimatedObjectNoCollision": {
        "CGeoMesh": 1,
        "CGeoOBBTree": 6,
        "CDspJointMap": 5,
        "CSkSkinInfo": 7,
        "CSkSkeleton": 2,
        "CDspMeshFile": 3,
        "DrwResourceMeta": 9,
        "AnimationSet": 8,
        "AnimationTimings": 4,
    },
    "AnimatedObjectCollision": {
        "CGeoMesh": 1,
        "CGeoOBBTree": 7,
        "CDspJointMap": 6,
        "CSkSkinInfo": 8,
        "CSkSkeleton": 3,
        "CDspMeshFile": 4,
        "DrwResourceMeta": 10,
        "AnimationSet": 9,
        "AnimationTimings": 5,
        "CGeoPrimitiveContainer": 2,
        "collisionShape": 11,
    },
    "StaticBuildingCollision": {
        "MeshSetGrid": 1,
        "CGeoPrimitiveContainer": 2,
        "collisionShape": 3,
    },
    "StaticBuildingNoCollision": {
        "MeshSetGrid": 1,
    },
    "AnimatedBuildingCollisionEffects": {
        "MeshSetGrid": 1,
        "AnimationSet": 5,
        "AnimationTimings": 4,
        "EffectSet": 2,
        "CGeoPrimitiveContainer": 3,
        "collisionShape": 6,
    },
    "AnimatedBuildingCollisionNoEffects": {
        "MeshSetGrid": 1,
        "AnimationSet": 4,
        "AnimationTimings": 3,
        "CGeoPrimitiveContainer": 2,
        "collisionShape": 5,
    },
    "StaticBuildingCollisionMesh": {
        "CGeoMesh": 1,
        "CGeoOBBTree": 5,
        "CDspJointMap": 4,
        "CDspMeshFile": 3,
        "DrwResourceMeta": 6,
        "CGeoPrimitiveContainer": 2,
        "collisionShape": 7,
    },
    "AnimatedBuildingCollisionMesh": {
        "CGeoMesh": 1,
        "CGeoOBBTree": 6,
        "CDspJointMap": 5,
        "CSkSkinInfo": 7,
        "CSkSkeleton": 3,
        "CDspMeshFile": 4,
        "DrwResourceMeta": 8,
        "CGeoPrimitiveContainer": 2,
        "collisionShape": 9,
    }
}

WriteOrder = {
    "AnimatedUnit": [
        "CDspJointMap",
        "CSkSkinInfo",
        "CSkSkeleton",
        "CDspMeshFile",
        "CDrwLocatorList",
        "DrwResourceMeta",
        "CGeoOBBTree",
        "CGeoMesh",
        "AnimationSet",
        "AnimationTimings",
        "EffectSet",
    ],
    "StaticObjectCollision": [
        "CDspJointMap",
        "CDspMeshFile",
        "DrwResourceMeta",
        "CGeoPrimitiveContainer",
        "CGeoOBBTree",
        "CGeoMesh",
        "collisionShape",
    ],
    "StaticObjectNoCollision": [
        "CDspJointMap",
        "CDspMeshFile",
        "DrwResourceMeta",
        "CGeoOBBTree",
        "CGeoMesh",
    ],
    "AnimatedObjectNoCollision": [
        "CDspJointMap",
        "CSkSkinInfo",
        "CSkSkeleton",
        "CDspMeshFile",
        "DrwResourceMeta",
        "CGeoOBBTree",
        "CGeoMesh",
        "AnimationSet",
        "AnimationTimings",
    ],
    "AnimatedObjectCollision": [
        "CDspJointMap",
        "CSkSkinInfo",
        "CSkSkeleton",
        "CDspMeshFile",
        "DrwResourceMeta",
        "CGeoPrimitiveContainer",
        "CGeoOBBTree",
        "CGeoMesh",
        "AnimationSet",
        "AnimationTimings",
        "collisionShape",
    ],
    "StaticBuildingCollision": [
        "MeshSetGrid",
        "CGeoPrimitiveContainer",
        "collisionShape",
    ],
    "StaticBuildingNoCollision": [
        "MeshSetGrid",
    ],
    "AnimatedBuildingCollisionEffects": [
        "MeshSetGrid",
        "AnimationSet",
        "AnimationTimings",
        "EffectSet",
        "CGeoPrimitiveContainer",
        "collisionShape",
    ],
    "AnimatedBuildingCollisionNoEffects": [
        "MeshSetGrid",
        "AnimationSet",
        "AnimationTimings",
        "CGeoPrimitiveContainer",
        "collisionShape",
    ],
    "StaticBuildingCollisionMesh": [
        "CDspJointMap",
        "CDspMeshFile",
        # maybe LocatorList?
        "DrwResourceMeta",
        "CGeoPrimitiveContainer",
        "CGeoOBBTree",
        "CGeoMesh",
        "collisionShape",
    ],
    "AnimatedBuildingCollisionMesh": [
        "CDspJointMap",
        "CSkSkinInfo",
        "CSkSkeleton",
        "CDspMeshFile",
        # maybe LocatorList?
        "DrwResourceMeta",
        "CGeoPrimitiveContainer",
        "CGeoOBBTree",
        "CGeoMesh",
        "collisionShape",
    ],
}
